// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// WireguardClient is the predicate function for wireguardclient builders.
type WireguardClient func(*sql.Selector)
