// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/boxjan/misc/pkg/knock/ent/predicate"
	"github.com/boxjan/misc/pkg/knock/ent/wireguardclient"
)

// WireguardClientQuery is the builder for querying WireguardClient entities.
type WireguardClientQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.WireguardClient
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WireguardClientQuery builder.
func (wcq *WireguardClientQuery) Where(ps ...predicate.WireguardClient) *WireguardClientQuery {
	wcq.predicates = append(wcq.predicates, ps...)
	return wcq
}

// Limit adds a limit step to the query.
func (wcq *WireguardClientQuery) Limit(limit int) *WireguardClientQuery {
	wcq.limit = &limit
	return wcq
}

// Offset adds an offset step to the query.
func (wcq *WireguardClientQuery) Offset(offset int) *WireguardClientQuery {
	wcq.offset = &offset
	return wcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wcq *WireguardClientQuery) Unique(unique bool) *WireguardClientQuery {
	wcq.unique = &unique
	return wcq
}

// Order adds an order step to the query.
func (wcq *WireguardClientQuery) Order(o ...OrderFunc) *WireguardClientQuery {
	wcq.order = append(wcq.order, o...)
	return wcq
}

// First returns the first WireguardClient entity from the query.
// Returns a *NotFoundError when no WireguardClient was found.
func (wcq *WireguardClientQuery) First(ctx context.Context) (*WireguardClient, error) {
	nodes, err := wcq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{wireguardclient.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wcq *WireguardClientQuery) FirstX(ctx context.Context) *WireguardClient {
	node, err := wcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WireguardClient ID from the query.
// Returns a *NotFoundError when no WireguardClient ID was found.
func (wcq *WireguardClientQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wcq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{wireguardclient.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wcq *WireguardClientQuery) FirstIDX(ctx context.Context) int {
	id, err := wcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WireguardClient entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WireguardClient entity is found.
// Returns a *NotFoundError when no WireguardClient entities are found.
func (wcq *WireguardClientQuery) Only(ctx context.Context) (*WireguardClient, error) {
	nodes, err := wcq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{wireguardclient.Label}
	default:
		return nil, &NotSingularError{wireguardclient.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wcq *WireguardClientQuery) OnlyX(ctx context.Context) *WireguardClient {
	node, err := wcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WireguardClient ID in the query.
// Returns a *NotSingularError when more than one WireguardClient ID is found.
// Returns a *NotFoundError when no entities are found.
func (wcq *WireguardClientQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wcq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{wireguardclient.Label}
	default:
		err = &NotSingularError{wireguardclient.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wcq *WireguardClientQuery) OnlyIDX(ctx context.Context) int {
	id, err := wcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WireguardClients.
func (wcq *WireguardClientQuery) All(ctx context.Context) ([]*WireguardClient, error) {
	if err := wcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return wcq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (wcq *WireguardClientQuery) AllX(ctx context.Context) []*WireguardClient {
	nodes, err := wcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WireguardClient IDs.
func (wcq *WireguardClientQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := wcq.Select(wireguardclient.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wcq *WireguardClientQuery) IDsX(ctx context.Context) []int {
	ids, err := wcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wcq *WireguardClientQuery) Count(ctx context.Context) (int, error) {
	if err := wcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return wcq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (wcq *WireguardClientQuery) CountX(ctx context.Context) int {
	count, err := wcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wcq *WireguardClientQuery) Exist(ctx context.Context) (bool, error) {
	if err := wcq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return wcq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (wcq *WireguardClientQuery) ExistX(ctx context.Context) bool {
	exist, err := wcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WireguardClientQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wcq *WireguardClientQuery) Clone() *WireguardClientQuery {
	if wcq == nil {
		return nil
	}
	return &WireguardClientQuery{
		config:     wcq.config,
		limit:      wcq.limit,
		offset:     wcq.offset,
		order:      append([]OrderFunc{}, wcq.order...),
		predicates: append([]predicate.WireguardClient{}, wcq.predicates...),
		// clone intermediate query.
		sql:    wcq.sql.Clone(),
		path:   wcq.path,
		unique: wcq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WireguardClient.Query().
//		GroupBy(wireguardclient.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (wcq *WireguardClientQuery) GroupBy(field string, fields ...string) *WireguardClientGroupBy {
	group := &WireguardClientGroupBy{config: wcq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := wcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return wcq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.WireguardClient.Query().
//		Select(wireguardclient.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (wcq *WireguardClientQuery) Select(fields ...string) *WireguardClientSelect {
	wcq.fields = append(wcq.fields, fields...)
	return &WireguardClientSelect{WireguardClientQuery: wcq}
}

func (wcq *WireguardClientQuery) prepareQuery(ctx context.Context) error {
	for _, f := range wcq.fields {
		if !wireguardclient.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wcq.path != nil {
		prev, err := wcq.path(ctx)
		if err != nil {
			return err
		}
		wcq.sql = prev
	}
	return nil
}

func (wcq *WireguardClientQuery) sqlAll(ctx context.Context) ([]*WireguardClient, error) {
	var (
		nodes = []*WireguardClient{}
		_spec = wcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &WireguardClient{config: wcq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, wcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (wcq *WireguardClientQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wcq.querySpec()
	_spec.Node.Columns = wcq.fields
	if len(wcq.fields) > 0 {
		_spec.Unique = wcq.unique != nil && *wcq.unique
	}
	return sqlgraph.CountNodes(ctx, wcq.driver, _spec)
}

func (wcq *WireguardClientQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := wcq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (wcq *WireguardClientQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   wireguardclient.Table,
			Columns: wireguardclient.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: wireguardclient.FieldID,
			},
		},
		From:   wcq.sql,
		Unique: true,
	}
	if unique := wcq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := wcq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wireguardclient.FieldID)
		for i := range fields {
			if fields[i] != wireguardclient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wcq *WireguardClientQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wcq.driver.Dialect())
	t1 := builder.Table(wireguardclient.Table)
	columns := wcq.fields
	if len(columns) == 0 {
		columns = wireguardclient.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wcq.sql != nil {
		selector = wcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wcq.unique != nil && *wcq.unique {
		selector.Distinct()
	}
	for _, p := range wcq.predicates {
		p(selector)
	}
	for _, p := range wcq.order {
		p(selector)
	}
	if offset := wcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WireguardClientGroupBy is the group-by builder for WireguardClient entities.
type WireguardClientGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wcgb *WireguardClientGroupBy) Aggregate(fns ...AggregateFunc) *WireguardClientGroupBy {
	wcgb.fns = append(wcgb.fns, fns...)
	return wcgb
}

// Scan applies the group-by query and scans the result into the given value.
func (wcgb *WireguardClientGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := wcgb.path(ctx)
	if err != nil {
		return err
	}
	wcgb.sql = query
	return wcgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (wcgb *WireguardClientGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := wcgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (wcgb *WireguardClientGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(wcgb.fields) > 1 {
		return nil, errors.New("ent: WireguardClientGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := wcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (wcgb *WireguardClientGroupBy) StringsX(ctx context.Context) []string {
	v, err := wcgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wcgb *WireguardClientGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = wcgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wireguardclient.Label}
	default:
		err = fmt.Errorf("ent: WireguardClientGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (wcgb *WireguardClientGroupBy) StringX(ctx context.Context) string {
	v, err := wcgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (wcgb *WireguardClientGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(wcgb.fields) > 1 {
		return nil, errors.New("ent: WireguardClientGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := wcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (wcgb *WireguardClientGroupBy) IntsX(ctx context.Context) []int {
	v, err := wcgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wcgb *WireguardClientGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = wcgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wireguardclient.Label}
	default:
		err = fmt.Errorf("ent: WireguardClientGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (wcgb *WireguardClientGroupBy) IntX(ctx context.Context) int {
	v, err := wcgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (wcgb *WireguardClientGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(wcgb.fields) > 1 {
		return nil, errors.New("ent: WireguardClientGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := wcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (wcgb *WireguardClientGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := wcgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wcgb *WireguardClientGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = wcgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wireguardclient.Label}
	default:
		err = fmt.Errorf("ent: WireguardClientGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (wcgb *WireguardClientGroupBy) Float64X(ctx context.Context) float64 {
	v, err := wcgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (wcgb *WireguardClientGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(wcgb.fields) > 1 {
		return nil, errors.New("ent: WireguardClientGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := wcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (wcgb *WireguardClientGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := wcgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wcgb *WireguardClientGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = wcgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wireguardclient.Label}
	default:
		err = fmt.Errorf("ent: WireguardClientGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (wcgb *WireguardClientGroupBy) BoolX(ctx context.Context) bool {
	v, err := wcgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (wcgb *WireguardClientGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range wcgb.fields {
		if !wireguardclient.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := wcgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wcgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (wcgb *WireguardClientGroupBy) sqlQuery() *sql.Selector {
	selector := wcgb.sql.Select()
	aggregation := make([]string, 0, len(wcgb.fns))
	for _, fn := range wcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(wcgb.fields)+len(wcgb.fns))
		for _, f := range wcgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(wcgb.fields...)...)
}

// WireguardClientSelect is the builder for selecting fields of WireguardClient entities.
type WireguardClientSelect struct {
	*WireguardClientQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (wcs *WireguardClientSelect) Scan(ctx context.Context, v interface{}) error {
	if err := wcs.prepareQuery(ctx); err != nil {
		return err
	}
	wcs.sql = wcs.WireguardClientQuery.sqlQuery(ctx)
	return wcs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (wcs *WireguardClientSelect) ScanX(ctx context.Context, v interface{}) {
	if err := wcs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (wcs *WireguardClientSelect) Strings(ctx context.Context) ([]string, error) {
	if len(wcs.fields) > 1 {
		return nil, errors.New("ent: WireguardClientSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := wcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (wcs *WireguardClientSelect) StringsX(ctx context.Context) []string {
	v, err := wcs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (wcs *WireguardClientSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = wcs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wireguardclient.Label}
	default:
		err = fmt.Errorf("ent: WireguardClientSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (wcs *WireguardClientSelect) StringX(ctx context.Context) string {
	v, err := wcs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (wcs *WireguardClientSelect) Ints(ctx context.Context) ([]int, error) {
	if len(wcs.fields) > 1 {
		return nil, errors.New("ent: WireguardClientSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := wcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (wcs *WireguardClientSelect) IntsX(ctx context.Context) []int {
	v, err := wcs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (wcs *WireguardClientSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = wcs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wireguardclient.Label}
	default:
		err = fmt.Errorf("ent: WireguardClientSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (wcs *WireguardClientSelect) IntX(ctx context.Context) int {
	v, err := wcs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (wcs *WireguardClientSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(wcs.fields) > 1 {
		return nil, errors.New("ent: WireguardClientSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := wcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (wcs *WireguardClientSelect) Float64sX(ctx context.Context) []float64 {
	v, err := wcs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (wcs *WireguardClientSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = wcs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wireguardclient.Label}
	default:
		err = fmt.Errorf("ent: WireguardClientSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (wcs *WireguardClientSelect) Float64X(ctx context.Context) float64 {
	v, err := wcs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (wcs *WireguardClientSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(wcs.fields) > 1 {
		return nil, errors.New("ent: WireguardClientSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := wcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (wcs *WireguardClientSelect) BoolsX(ctx context.Context) []bool {
	v, err := wcs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (wcs *WireguardClientSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = wcs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wireguardclient.Label}
	default:
		err = fmt.Errorf("ent: WireguardClientSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (wcs *WireguardClientSelect) BoolX(ctx context.Context) bool {
	v, err := wcs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (wcs *WireguardClientSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := wcs.sql.Query()
	if err := wcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
