// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/boxjan/misc/pkg/knock/ent/predicate"
	"github.com/boxjan/misc/pkg/knock/ent/wireguardclient"
)

// WireguardClientDelete is the builder for deleting a WireguardClient entity.
type WireguardClientDelete struct {
	config
	hooks    []Hook
	mutation *WireguardClientMutation
}

// Where appends a list predicates to the WireguardClientDelete builder.
func (wcd *WireguardClientDelete) Where(ps ...predicate.WireguardClient) *WireguardClientDelete {
	wcd.mutation.Where(ps...)
	return wcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wcd *WireguardClientDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(wcd.hooks) == 0 {
		affected, err = wcd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WireguardClientMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wcd.mutation = mutation
			affected, err = wcd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(wcd.hooks) - 1; i >= 0; i-- {
			if wcd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = wcd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wcd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (wcd *WireguardClientDelete) ExecX(ctx context.Context) int {
	n, err := wcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wcd *WireguardClientDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: wireguardclient.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: wireguardclient.FieldID,
			},
		},
	}
	if ps := wcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, wcd.driver, _spec)
}

// WireguardClientDeleteOne is the builder for deleting a single WireguardClient entity.
type WireguardClientDeleteOne struct {
	wcd *WireguardClientDelete
}

// Exec executes the deletion query.
func (wcdo *WireguardClientDeleteOne) Exec(ctx context.Context) error {
	n, err := wcdo.wcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{wireguardclient.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wcdo *WireguardClientDeleteOne) ExecX(ctx context.Context) {
	wcdo.wcd.ExecX(ctx)
}
