// Code generated by entc, DO NOT EDIT.

package wireguardclient

import (
	"time"
)

const (
	// Label holds the string label denoting the wireguardclient type in the database.
	Label = "wireguard_client"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDestroyedAt holds the string denoting the destroyed_at field in the database.
	FieldDestroyedAt = "destroyed_at"
	// FieldExpired holds the string denoting the expired field in the database.
	FieldExpired = "expired"
	// FieldIdentify holds the string denoting the identify field in the database.
	FieldIdentify = "identify"
	// FieldServerPrivateKey holds the string denoting the server_private_key field in the database.
	FieldServerPrivateKey = "server_private_key"
	// FieldClientPrivateKey holds the string denoting the client_private_key field in the database.
	FieldClientPrivateKey = "client_private_key"
	// FieldNetifName holds the string denoting the netif_name field in the database.
	FieldNetifName = "netif_name"
	// FieldPeerAddr holds the string denoting the peer_addr field in the database.
	FieldPeerAddr = "peer_addr"
	// FieldListenAddr holds the string denoting the listen_addr field in the database.
	FieldListenAddr = "listen_addr"
	// FieldAllocCidr holds the string denoting the alloc_cidr field in the database.
	FieldAllocCidr = "alloc_cidr"
	// FieldServerAddress holds the string denoting the server_address field in the database.
	FieldServerAddress = "server_address"
	// FieldClientAddress holds the string denoting the client_address field in the database.
	FieldClientAddress = "client_address"
	// FieldReceiveBytes holds the string denoting the receive_bytes field in the database.
	FieldReceiveBytes = "receive_bytes"
	// FieldTransmitBytes holds the string denoting the transmit_bytes field in the database.
	FieldTransmitBytes = "transmit_bytes"
	// Table holds the table name of the wireguardclient in the database.
	Table = "wireguard_clients"
)

// Columns holds all SQL columns for wireguardclient fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDestroyedAt,
	FieldExpired,
	FieldIdentify,
	FieldServerPrivateKey,
	FieldClientPrivateKey,
	FieldNetifName,
	FieldPeerAddr,
	FieldListenAddr,
	FieldAllocCidr,
	FieldServerAddress,
	FieldClientAddress,
	FieldReceiveBytes,
	FieldTransmitBytes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDestroyedAt holds the default value on creation for the "destroyed_at" field.
	DefaultDestroyedAt func() time.Time
	// DefaultExpired holds the default value on creation for the "expired" field.
	DefaultExpired bool
	// DefaultIdentify holds the default value on creation for the "identify" field.
	DefaultIdentify string
	// ServerPrivateKeyValidator is a validator for the "server_private_key" field. It is called by the builders before save.
	ServerPrivateKeyValidator func(string) error
	// ClientPrivateKeyValidator is a validator for the "client_private_key" field. It is called by the builders before save.
	ClientPrivateKeyValidator func(string) error
	// NetifNameValidator is a validator for the "netif_name" field. It is called by the builders before save.
	NetifNameValidator func(string) error
	// DefaultPeerAddr holds the default value on creation for the "peer_addr" field.
	DefaultPeerAddr string
	// ListenAddrValidator is a validator for the "listen_addr" field. It is called by the builders before save.
	ListenAddrValidator func(string) error
	// AllocCidrValidator is a validator for the "alloc_cidr" field. It is called by the builders before save.
	AllocCidrValidator func(string) error
	// ServerAddressValidator is a validator for the "server_address" field. It is called by the builders before save.
	ServerAddressValidator func(string) error
	// ClientAddressValidator is a validator for the "client_address" field. It is called by the builders before save.
	ClientAddressValidator func(string) error
	// DefaultReceiveBytes holds the default value on creation for the "receive_bytes" field.
	DefaultReceiveBytes uint64
	// DefaultTransmitBytes holds the default value on creation for the "transmit_bytes" field.
	DefaultTransmitBytes uint64
)
